### ISSUE TITLE
404 for M2MQTT under .NET / dotNet

### ISSUE THREAD

**Issue by mviranyi** [mqtt/mqtt.github.io#11]
Under [.NET / dotNET](https://github.com/mqtt/mqtt.github.io/wiki/libraries#net--dotnet) the Codeplex link to the M2MQTT library isn't working anymore. Instead it is relocating to  
https://www.codeplex.com/site/pagenotfound

> “A forge may have holes
> Based on the page you look for
> We think you found one”
> 
> “If a link falls down
> And nobody is around
> It will not be heard”

_and so on .._

Is it maybe only this project now: https://github.com/ppatierno/m2mqtt ?

**Comment by kartben** [comment]
poke @ppatierno

**Comment by andypiper** [comment]
It's just a wiki page so anyone can make the update, unless there's some issue with permissions in this repo?

**Comment by ppatierno** [comment]
I just modified it but it's temporary because in a few days M2Mqtt will be on the official Eclipse Paho GitHub account.

**Comment by B-Weiss** [comment]
Thanks for your contribution to mqtt.org. The website has been relaunched in August 2020 and we are closing the old issues. Feel free to submit a pull request or re-open the issue, if your issue is still relevant.
