### ISSUE TITLE
Eclipse Paho is not a MQTT server

### ISSUE THREAD

**Issue by ali-khalili** [mqtt/mqtt.github.io#12]
In the list of servers, [Eclipse Paho](http://www.eclipse.org/paho/) is mentioned as a server whereas it is actually a set of client implementation in different languages and indeed it is listed in clients as well.

**Comment by kartben** [comment]
Feel free to directly edit the wiki :)

**Comment by andypiper** [comment]
The entry on that page specifically says that the Paho project is hosting a mosquitto instance.

**Comment by eastwoodwang** [comment]
i install the Android module and install into my cellphones, it can communicate with iot.eclipse.org:1883
The iot.eclipse.org still use mosquitto or Apollo or another?

**Comment by andypiper** [comment]
mosquitto

**Comment by eastwoodwang** [comment]
thanks for your reply, one more question i install Mosquitto server in Window 7 in my PC, and i can connect it with Chrome plugin MQTT, but it looks like that i cannot connect it with my app demo. The app demo is from paho git.

**Comment by eastwoodwang** [comment]
ok, i think i fix the issue, forget to close the PC firewall. Thanks

**Comment by zjl13297033490** [comment]
How to install Mosquitto server in windows10 in my PC?

**Comment by knolleary** [comment]
@zjl13297033490 sorry, this is not a support forum for mosquitto. Head over to mosquitto.org

**Comment by luoqianer** [comment]
wow, what is the difference between "MQTT Server" and "MQTT Broker"?I think it should be the same.
