### ISSUE TITLE
TLS (AWS IoT) support for Windows Universal (IoT)

### ISSUE THREAD

**Issue by lbknuth** [mqtt/mqtt.github.io#13]
I see that the Client constructor that includes the two x509 certs is missing when I nuget into a Visual Studio Windows Universal project.  I don't think I can connect a Windows 10 IoT Core device to the AWS IoT service any other way (TLS is required).  Is support on the dev roadmap?  Is it a simple enough solution for me to implement in the source (and drop the use of nuget for now)?

**Comment by knolleary** [comment]
Hi, this site isn't associated with any specific client library. For this sort of question you should contact the maintainer of the client you are using.

**Comment by francoisvdm** [comment]
Hey! 


We've  recently  vizited a  very beautiful place and  wanted to share  that with you, check it  out, it's amazing <http://shypremyro.emilysenchantedimages.com/e4hnk>


Alf Close
