### ISSUE TITLE
MQTT via SCTP

### ISSUE THREAD

**Issue by y0urself** [mqtt/mqtt.github.io#15]
Is there any possibility to use SCTP Protocol for MQTT?
And is there any possibility to change the Brokers Port?

**Comment by kaleemullah360** [comment]
Which Broker you are talking about ?
read the Broker documentation and feature listed by Broker developers.

**Comment by knolleary** [comment]
This issue tracker is for the mqtt.org website. It isn't a place to get support for individual clients or ask about the protocol itself.

If this is still an issue please use:
 - For questions about the protocol itself - https://groups.google.com/forum/#!forum/mqtt
 - For question about an individual broker or client implementation - use whatever support forum they provide.

**Comment by y0urself** [comment]
Yeah. Thanks. The question is 4 years old.
