### ISSUE TITLE
Mosca doesn't support Clustering ???

### ISSUE THREAD

**Issue by ssashita** [mqtt/mqtt.github.io#16]
Hi,
 As part of MQTT broker evaluation, I set up a clustered Mosca set up using alternatives of MongoDB and Redis. But your table says Mosca does not support clustering. I am assuming you have deeply researched before creating the information, so can you please let me know more, so that I am sure I have not missed something critical

Thanks,
Sachin

**Comment by andypiper** [comment]
this is a public wiki so updates to information depend on community contribution. That information has not been updated for some time, so it could well be outdated.

**Comment by B-Weiss** [comment]
Thanks for your contribution to mqtt.org. The website has been relaunched in August 2020 and we are closing the old issues. Feel free to submit a pull request or re-open the issue, if it is still relevant.
