### ISSUE TITLE
Server Support list

### ISSUE THREAD

**Issue by krital** [mqtt/mqtt.github.io#19]
Hello,

I work for Software AG Universal Messaging R&D team. I would like to update some information you have about our product on the Server Support list URL. 

https://github.com/mqtt/mqtt.github.io/wiki/Server%20support

Any preferred way of doing that?

Thanks,

Alex Kritikos

**Comment by knolleary** [comment]
Hi - being a wiki, go ahead and make you edits :)

**Comment by krital** [comment]
Thanks Nick!
