### ISSUE TITLE
Escaped username and password in URI

### ISSUE THREAD

**Issue by marclennox** [mqtt/mqtt.github.io#21]
I'm trying to use the URI connection format with username and password in the URI, however if the username or password contain special characters, my understanding is that you are supposed to CGI escape them (percent escape).

It seems though that this library does not decode the username and password, so authentication fails.

Would you accept a PR that de-escapes them?

**Comment by knolleary** [comment]
Hi - this is as issue list for a wiki about MQTT. It is not a specific library.

I suggest you need to raise this against whatever library you are using.

**Comment by marclennox** [comment]
My apologies I posted this to the wrong repo

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
