### ISSUE TITLE
Multiple input queues

### ISSUE THREAD

**Issue by slazareanu** [mqtt/mqtt.github.io#22]
Using MQTTAsync, it seems that the instantiation of multiple clients by the same app leads to multiple input queues. Unfortunately, it looks that there is no mechanism to specify in which order the queues should be served. MessageArrived callback seems to pick messages at random between the input queues. Can a scheduling policy on how to serve the queues be specified? Something like: round-robin or multilevel queues.

**Comment by knolleary** [comment]
Hi, this is an issue list for the mqtt wiki. It isn't associated with any particular implementation.

If you have a question for an implementation, you should use whatever mailing list/issue tracker that implementation provides.

Thanks!
