### ISSUE TITLE
'$SYS/broker/clients/#' does not work to connection mqtt over websocket?

### ISSUE THREAD

**Issue by tidanilocarvalho** [mqtt/mqtt.github.io#23]
I have a mosquitto broker configured using tcp and websocekt, but i can't see my clients connecteds when them use mqtt over websocket.

I'm using this topic '$SYS/broker/clients/connected'

This is normal?

**Comment by knolleary** [comment]
Hi - this is an issue list for the mqtt.org website. If you want support for a particular implementation please use the appropriate mailing list/issue tracker. Thanks.
