### ISSUE TITLE
consider adding my project 2 Client libraries?

### ISSUE THREAD

**Issue by xljiulang** [mqtt/mqtt.github.io#24]
hi, i have a MQTT client respository that implement by .net at [github](https://github.com/xljiulang/Paho.MqttDotnet), and  lots of .net-developers will need it, i think. The respository is a .net wrapper for eclipse/paho.mqtt.c

**Comment by andypiper** [comment]
the wiki should be editable by any Github user so you are welcome to add it -> https://github.com/mqtt/mqtt.github.io/wiki

**Comment by xljiulang** [comment]
@andypiper got it，thank you very much.
