### ISSUE TITLE
Ansible role: debops.mosquitto

### ISSUE THREAD

**Issue by AnBuKu** [mqtt/mqtt.github.io#25]
Maybe interesting to MQTT project:

- https://github.com/debops/ansible-mosquitto
- https://docs.debops.org/en/latest/ansible/roles/ansible-mosquitto/docs/index.html

**Comment by knolleary** [comment]
Please consider sharing on the community mailing list: http://groups.google.com/group/mqtt

**Comment by AnBuKu** [comment]
@knolleary I love to share. Unfortunately I have no Google account and subscribing just for one information looks a bit overdone to me. But please, feel free to inform MQTT community about debops/ansible-mosquitto if you think it's useful to them.

As well maybe interesting to MQTT community might be https://en.wikipedia.org/wiki/MQTT for adding content and improving the article. Finally such thing as Wikipedia are some kind of marketing or public relation for MQTT and might promote the use of MQTT,
