### ISSUE TITLE
A issue of connection about MQTT

### ISSUE THREAD

**Issue by Huang9495** [mqtt/mqtt.github.io#28]
A issue of connection about MQTT after I install the MQTT.js from Github (https://github.com/mqttjs/MQTT.js) , a issue is take place ,my environment : system: Ubuntu14.04; MQTT:2.9.1; mosquitto :1.4.12; 

**# The code of my object is here:**

var mqtt = require('mqtt');
var client = mqtt.createClient(1883, 'localhost',{clientId:'1',clean:false});
client.subscribe('datasend')
client.on('datasend',function(client){
console.log('client connected');
});
client.on('message', function (topic, message) {
console.log(message.toString())
})
setInterval(function(){
client.publish('datasend','1');
console.log('datasend');
},2000);

# **The error of my test is here:**

/home/kris-allen/mqtt/mqtt/MQTT.js/example1.js:3
var client = mqtt.createClient(1883, 'localhost');
                  ^
TypeError: mqtt.createClient is not a function
    at Object.<anonymous> (/home/kris-allen/mqtt/mqtt/MQTT.js/example1.js:3:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by knolleary** [comment]
Hi, this is the mqtt.org website issue tracker. You've identified the git repository of the client you are using - you should raise an issue against it.

**Comment by Huang9495** [comment]
Hi @knolleary  Thank you for your help ! But I don't realize the mean of 'you should raise an issue against it'. Whether the 'it' is point to the git repository? And I know the createclient() is compatible for the MQTT. Now I don't know how to point my issue. Can you help me ? Thanks @knolleary

**Comment by knolleary** [comment]
You have raised an issue against the mqtt.org website - that is not going to help you with a specific client implementation.

You are using the MQTT.js client. If you have a question/problem with that client, you should direct your question at that client's community. Your original comment points to that client's repository - so you know what repository you should raise the issue in. https://github.com/mqttjs/MQTT.js/issues

**Comment by Huang9495** [comment]
Oh! @knolleary Thank you .I know how to do now !Thank you for you help again!
