### ISSUE TITLE
the question about protocol（3.1.2.4 Clean Session ） 

### ISSUE THREAD

**Issue by penghuster** [mqtt/mqtt.github.io#29]
In 3.1.2.4 Clean Session，the first Non normative comment says “To ensure consistent state in the event of a failure, the Client should repeat its attempts to  connect with CleanSession set to 1, until it connects successfully.  ”
To ensure consistent state, we should reconnect with CleanSession set to 1 ?
why ?
As I understand. if we want to keep the state consistent, we should connect with   CleanSession set to 0. then we can reuse the session state of last connection. but the protocol said like that, why? whether do I misunderstand it?
thanks.

**Comment by knolleary** [comment]
Hi, for questions about the protocol please use the Google group mailing list linked from the community page. This issue tracker is for a website.
