### ISSUE TITLE
Packets being dropped

### ISSUE THREAD

**Issue by pedrombmachado** [mqtt/mqtt.github.io#30]
Dear all,
I am using mqtt on a cluster composed of 376 devices. Nevertheless, Packets are being dropped with a high frequency. I have a multi-threads implementation with 16 topics and 6 ports. 
I am using the methods loop_start() and loop_stop() and tried with loop_forever().
Any suggestions why the packets are being dropped?
Many thanks
Pedro

**Comment by knolleary** [comment]
Hi,

this is the issue tracker for the mqtt.org website. It is not somewhere to get support for particular implementations.

You don't say anything about which client/server you're using so I can't point you in the right direction; but you should contact the maintainers of whatever you are using.

Thanks!
