### ISSUE TITLE
New tool to test MQTT Observer

### ISSUE THREAD

**Issue by fauresystems** [mqtt/mqtt.github.io#32]
I would recommend to test [MQTT Observer, free open source client to display messages](https://github.com/fauresystems/mqtt-observer). It was created as an helper in an Escape Room 2.0 project to monitor several Arduinos and Raspberries.

You create observation displays to filter out some topics, to filter out some messages starting with specific strings and to display fool topic or extracted correspondent.

Correspondents (Arduino/Raspberry names) are extracted from topic syntax with a regex you can change.

Clean wills: identify forgotten topics with remaining wills, and select wills to reset.

Save server and observation settings as sessions, to retrieve further.

**Comment by B-Weiss** [comment]
Thanks for your contribution to mqtt.org. The website has been relaunched in August 2020 and we are closing the old issues. Feel free to submit a pull request or re-open the issue, if it is still relevant.
