### ISSUE TITLE
not support C51?

### ISSUE THREAD

**Issue by wuweiit** [mqtt/mqtt.github.io#33]
not support C51?

**Comment by knolleary** [comment]
Hi @wuweiit 

this is an issue tracker for the mqtt.org website. If you have questions about the protocol, you may want to use the Google Group mailing list - https://groups.google.com/forum/#!forum/mqtt

You will need to provide a bit more information in your question - not clear what you mean by C51. Are you looking for an MQTT client or broker implementation?
