### ISSUE TITLE
After 'connected' , still  trigger 'connect' event . And the topic is not resubscribed.

### ISSUE THREAD

**Issue by AlwaysSkylll** [mqtt/mqtt.github.io#36]
After 'connected' , still  trigger 'connect' event . 
And the topic is not resubscribed while publish action is ok.

**Comment by knolleary** [comment]
Hi, this is an issue tracker for the mqtt.org website.

If you are have trouble with a particular client library, you should raise it easier with them.

**Comment by AlwaysSkylll** [comment]
👌 thank you
