### ISSUE TITLE
no subscription possible

### ISSUE THREAD

**Issue by muellerjm** [mqtt/mqtt.github.io#38]
the system:
Ubuntu 17.10
PHP 7.1
libmosquitto 1.4.12
extension 0.4.0

the installation works well. I have problems with original sample code subscription (publish works fine). when I open the sample code in the browser, nothing happens. (The browser is in a loop - that's fine) I test with mqttfx and mosquitto_pub. What am I doing wrong?

``<?php
define('BROKER', '10.1.1.2');
define('PORT', 1883);
define('CLIENT_ID', "pubclient_" + getmypid());

$client = new Mosquitto\Client(CLIENT_ID);
$client->onConnect('connect');
$client->onDisconnect('disconnect');
$client->onSubscribe('subscribe');
$client->onMessage('message');
$client->connect(BROKER, PORT, 60);
$client->subscribe('#', 1); // Subscribe to all messages

$client->loopForever();

function connect($r) {
        echo "Received response code {$r}\n";
}

function subscribe() {
        echo "Subscribed to a topic\n";
}
 
thank you guys

**Comment by knolleary** [comment]
This is an issue tracker for the mqtt website. We don't provide any support for client implementations. Sorry!
