### ISSUE TITLE
Homie convention

### ISSUE THREAD

**Issue by nicola-lunghi** [mqtt/mqtt.github.io#39]
Can you put a reference to the HOMIE convention in the https://github.com/mqtt/mqtt.github.io/wiki/Conventions page?

https://github.com/homieiot/convention

Thanks
Nick

**Comment by B-Weiss** [comment]
Thanks for your contribution to mqtt.org. The website has been relaunched in August 2020 and we are closing the old issues. Feel free to submit a pull request or re-open the issue, if it is still relevant.
