### ISSUE TITLE
why message id only use two byte?

### ISSUE THREAD

**Issue by yjp211** [mqtt/mqtt.github.io#4]
we can only identify a message by message id in publish ack protocol,  it't too short..

**Comment by knolleary** [comment]
Hi @yjp211 

this issue list is not the best place to ask questions about MQTT.

You should ask them on the mqtt community mailing list, linked from here: http://mqtt.org/get-involved

Regards,
Nick

**Comment by wxzqq** [comment]
That's very kind of you
