### ISSUE TITLE
About URI

### ISSUE THREAD

**Issue by dfang** [mqtt/mqtt.github.io#40]
referring to `https://github.com/mqtt/mqtt.github.io/wiki/URI-Scheme` 

when username contains ":", what is the right MQTT_SERVER ?

and

for go client `https://github.com/eclipse/paho.mqtt.golang`,
`mqtt://` won't work, err msg is "Network Error : Unknown protocol", but `tcp://` works

**Comment by knolleary** [comment]
Please use the client's own mailing list or issue tracker to ask questions about it.

This issue tracker is for the errors in the website content.
