### ISSUE TITLE
Is Apache storm also support MQTT ?

### ISSUE THREAD

**Issue by E312232595** [mqtt/mqtt.github.io#43]

**Comment by E312232595** [comment]
http://storm.apache.org/releases/1.0.6/storm-mqtt.html

**Comment by knolleary** [comment]
This issue tracker is for the mqtt.org website. It isn't a place to get support for individual clients or ask about the protocol itself.

If this is still an issue please use:
 - For questions about the protocol itself - https://groups.google.com/forum/#!forum/mqtt
 - For question about an individual broker or client implementation - use whatever support forum they provide.
