### ISSUE TITLE
Clustering/Mirroring issue with MQTT

### ISSUE THREAD

**Issue by abhi-dwivedi** [mqtt/mqtt.github.io#45]
Team

We are having issue with clustering/mirroring in rabbitmq with mqtt versions: 3.6.15 Erlang 19.3

So we where having data discrepancies while doing pub/sub in 2 node cluster.
Publish with retaining flag
One time we are getting another data while doing subscribe and next time we are doing subscribe we are getting different data on different client id.
Doing it from MQTTfx. 

Even we enable the mirror also:
rabbitmqctl set_policy ha-all "" '{"ha-mode":"all","ha-sync-mode":"automatic"}'

**Comment by knolleary** [comment]
This issue tracker is for the website.

If you have a problem with rabbitmq, please use their mailing list/support forum
