### ISSUE TITLE
how to build mqtt and kafka to save the messages

### ISSUE THREAD

**Issue by Linuxlovers** [mqtt/mqtt.github.io#51]
how to build mqtt and kafka to save the messages?

i try to 
evokly/kafka-connect-mqtt: mqtt (source) conncetor for kafka
https://github.com/evokly/kafka-connect-mqtt

but i  get 
![image](https://user-images.githubusercontent.com/23232806/74120102-205d0e80-4bfd-11ea-9319-13e6155d73a0.png)

**Comment by knolleary** [comment]
This is the repo for the Mqtt website, not general support.

If you are having issues with a particular library, raise the issue against that library.
