### ISSUE TITLE
Websocket issue

### ISSUE THREAD

**Issue by deeppatel2193** [mqtt/mqtt.github.io#52]
Hello,
I have configured paho mqtt for subscribe the data from mqtt but facing web socket related issue.
Error:
`Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.`

I have using mosquitto and vernemq both as mqtt broker but facing same issue.
I have configured below lines in configuration file of mosquitto.

> listener 1883 localhost
>   
> listener 8083
> protocol websockets

Do you have any solution for that?
Please give me solution.

**Comment by knolleary** [comment]
This is an issue tracker for the MQTT.org website. It is not a support channel for any particular client implementation.

If you are having issues with the Paho client, please use their issue tracker or forum.
