### ISSUE TITLE
Presence with multiple clients

### ISSUE THREAD

**Issue by considerate** [mqtt/mqtt.github.io#7]
How would you go about implementing presence for multiple clients that share the same user id?

If client A connects first and publishes a retained message to a online/:userid topic and then client B publishes a similar message to the same topic because both clients share the same user id then if I have read the specification correctly only client B's message is retained. So what should be done in the case that client A (or B) now disconnects. One client is still online but the LWT message will be published notifying all other clients that the user is no longer online.

Do you suggest using some sort of counter (which leads to complexity) or should the client that was still online publish a new message notifying everyone that the user indeed is online (causing the 'now offline' LWT message being sent and the user logging out and then in again)? Is there any better way to handle this?

**Comment by knolleary** [comment]
Hi,

you cannot have two clients that share the same id.

The id must be unique for each client as it is used to associate all of the session state, such as inflight messages.

If a second client connects with the same id as an existing client, the first client is first disconnected by the server.

**Comment by considerate** [comment]
Let me clarify: I am not suggesting to have two clients with the same client id. What I am asking for is how you would go about checking if any client with a given "username" (in my case an id) is online. That is I would like a topic where I can see if client A (with username "Joe") or client B (also with username "Joe") is online. The issue is with client A having a LWT message saying that "Joe" now is offline even though client B (logged in as "Joe") is still online.

**Comment by andypiper** [comment]
This issue tracker is intended for the mqtt.org website and wiki - you're probably better off asking this kind of question on the MQTT protocol google group -> https://groups.google.com/forum/?hl=en#!forum/mqtt

**Comment by considerate** [comment]
Thank you, I will try that :smile:
