### ISSUE TITLE
What are real hardware devices that use MQTT

### ISSUE THREAD

**Issue by WilliamKinaan** [mqtt/mqtt.github.io#8]
Hello,

I am looking for a real hardware devices that use MQTT. All i could get is LanuchPad with BoosterPack. I would like to know if really there are hardware for MQTT. Something as mature as buying a sensor, configure the topic and the broker and let it go.

Thanks

**Comment by knolleary** [comment]
Hi, 
Please use the community mailing list for general mqtt questions - http://mqtt.org/get-involved

This issue list is for problems with the wiki/website content.

Thanks, Nick

**Comment by andypiper** [comment]
You can find a few examples on the ["things"](https://github.com/mqtt/mqtt.github.io/wiki/things) page of the MQTT wiki.
