### ISSUE TITLE
Links broken under subsection : MQTT and Android

### ISSUE THREAD

**Issue by nisrulz** [mqtt/mqtt.github.io#9]
The following links are broken or not working anymore please update 
- http://tokudu.com/2010/how-to-implement-push-notifications-for-android/
- http://rethinksun.com./main/?p=458
- http://rethinksun.com./main/?p=490
- http://wilhall.com/2012/04/29/imrek-android-group-chat-app-using-mqtt/

**Comment by birben** [comment]
Following links in [**Example Uses**] (https://github.com/mqtt/mqtt.github.io/wiki/Example%20Uses) are also broken.
* Home Automation
  * [Power Monitoring] (http://stanford-clark.com/power.html)
  * [Gardening] (http://ww1.ossmedicine.org/)
  * [Android/TV/Burglar detection system] (http://www.hardill.me.uk/wordpress/?p=204)
  * [MQTT<>LLAP bridge example] (https://github.com/mqtt/mqtt.github.io/wiki/https///github.com/dpslwk/OpenKontrol-Gateway)
  * [homA] (https://github.com/mqtt/mqtt.github.io/wiki/https///github.com/binarybucks/homA)

**Comment by andypiper** [comment]
Thanks for the notes - this is a wiki so feel free to edit. I'll try to fix these when I can.

**Comment by francoisvdm** [comment]
Hey! 


We've  recently  vizited a  very beautiful place and  wanted to share  that with you, check it  out, it's amazing <http://shypremyro.emilysenchantedimages.com/e4hnk>


Alf Close
